apiVersion: batch/v1
kind: Job
metadata:
  name: train-ml-k8s
spec:
  template:
    spec:
      containers:
      - name: train-ml-k8s
        imagePullPolicy: Always
        image: ananth98/mnist-train
        command: ["bash", "/app/run.sh"]
        resources:
          limits:
            nvidia.com/gpu: 1 # requesting 1 GPU
      restartPolicy: Never
  backoffLimit: 0